[package]
name = "mandelbrot_set"
version = "0.1.0"
authors = ["LAPTOP-1FSSOH6T\\ykhr7 <ykhr7121rkhy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.37"